name: booksearch # You can also change this to another name to avoid warning with existing group. 
services:
  frontend:
    container_name: bk-frontend
    build: .
    ports:
      - ${NGINX_PORT}:3990
    networks:
      - booksearch_pf-net
    environment:
      - NGINX_PROXY=${NGINX_PROXY}
      - NGINX_PORT=${NGINX_PORT}
networks:
  booksearch_pf-net: # Check by using `docker network ls` command
    external: true
